Parameters:
  Versioning:
    Default: 'Suspended'
    Type: String
    AllowedValues: [Enabled, Suspended]
  Owner:
    Type: String
    Description: 'Bucket Owner'

  Department:
    Type: String
    Description: 'Department Name'
    Default: 'IT'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: 'new-encrypted-file'
        AccessControl: Private
        VersioningConfiguration:
          Status: !Ref Versioning
        BucketEncryption:
          ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: arn:aws:kms:us-east-1:824812782977:key/52bdacad-d6ac-405d-8347-116428a88996         
        Tags:
        - Key : Owner
          Value: !Ref Owner
        - Key : Department
          Value: !Ref Department
